config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root to: redirect('/favorite-foods')

  get 'favorite-foods', to: 'pages#foods'
  get 'songs', to: 'pages#songs', as: 'songs'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def foods
    render :foods
  end

  def songs
    render :songs
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FavoritesList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/foods.html.erb
<h1>Favorite Foods</h1>

<% time = Time.now %>
<%= time %>

<ul>
  <li><%= image_tag 'salsa.jpeg' %> Salsa</li>
  <li>Cheese</li>
  <li>Eggs</li>
  <li>Bread</li>
</ul>

<a href="/favorite-songs">My Favorite Songs</a>
<%= link_to 'My Favorite Songs', '/favorite-songs' %>
<%= link_to 'My Favorite Songs', songs_path %>

app/views/pages/songs.html.erb
<h1>Favorite Songs</h1>

<ul>
  <li>The Gummy Bears Song by Gummy Bear</li>
  <li>1944 by Jamala</li>
</ul>